export const Category = {
	VEGETABLES: {
		name: 'Obst & Gemüse',
		items: [
			'Aubergine',
			'Avocado',
			'Blumenkohl',
			'Babyspinat, frisch',
			'Brokkoli',
			'Champignons',
			'Riesenchampignons',
			'Champignons, Konserve',
			'Cherrytomaten',
			'Eisbergsalat',
			'Erbsen, tiefgekühlt',
			'Schalotte',
			'Feldsalat',
			'Frühlingszwiebeln',
			'Getrocknete Tomaten',
			'Gewürzgurken',
			'Gurken, eingelegt',
			'Karotte',
			'Karotten',
			'Kartoffel',
			'Kartoffeln',
			'Kichererbsen, Konserve',
			'Kidneybohnen, Konserve',
			'Schwarze Bohnen, Konserve',
			'Kirschtomaten',
			'Mais',
			'Mais, Konserve',
			'Oliven, entkernt',
			'Orange',
			'Paprika, gelb',
			'Paprika, grün',
			'Paprika, rot',
			'Rucola',
			'Salatgurke',
			'Salatmischung',
			'Schwarze Bohnen, Konserve',
			'Spitzpaprika, rot',
			'Süßkartoffeln',
			'Tomate',
			'Tomaten',
			'Tomaten, passiert',
			'Tomaten, stückig',
			'Erbsen, tiefgekühlt',
			'Paprika',
			'Paprika, rot',
			'Petersilie, frisch',
			'Riesenchampignons',
			'Weintrauben',
			'Weintrauben, grün',
			'Weintrauben, rot',
			'Zucchini',
			'Zitrone',
			'Zitrone, bio',
			'Zitronen',
			'Zwiebel',
			'Zwiebeln',
		],
	},
	DRINKS: {
		name: 'Getränke',
		items: [
			'Orangensaft, frisch',
			'Reiswein',
			'Wasser',
			'Haferdrink, ungesüßt',
			'Milch',
			'Vollmilch',
			'Hafermilch',
			'Haferdrink',
		],
	},
	HERBS: {
		name: 'Kräuter, Öle und Gewürze',
		items: [
			'Basilikum, frisch',
			'Dill, frisch',
			'Koriander',
			'Koriander, frisch',
			'Kreuzkümmel, gemahlen',
			'Knoblauchpulver',
			'Kümmel, gemahlen',
			'Basilikum, frisch',
			'Minze, frisch',

			'Knoblauchzehe',
			'Knoblauchzehen',
			'Ingwer, frisch',
			'Italienische Kräuter',
			'Italienische Kräutermischung',
			'Oregano, gerebelt',
			'Paprikapulver',
			'Paprikapulver, edelsüß',
			'Petersilie, frisch',
			'Thymian',
			'Petersilie, gehackt',
			'Pfeffer',
			'Salbei, frisch',
			'Salz',
			'Basilikum, frisch',
			'Knoblauchpulver',
			'Thymian, gerebelt',
			'Thymian, getrocknet',
			'Rosmarin, frisch',
			'Pfeffer und Salz',
		],
	},
	BREAD: {
		name: 'Brot, Back, Beilagen',
		items: [
			'Baguette',
			'Cashewkerne',
			'Mandeln',
			'Mehl',
			'Couscous',
			'Goldhirse',
			'Pankomehl',
			'Hefeflocken',
			'Haferflocken, zart',
			'Hefe, frisch',
			'Kürbiskerne',
			'Vollkornbrötchen',
			'Vollkornnudeln',
			'Vollkornreis',
			'Vollkorn-Fusilli',
			'Walnusskerne, gemahlen',
			'Sesamsamen',
			'Sesamsamen, geröstet',
			'Pitabrote',
			'Quinoa',
			'Ramen Nudeln',
			'Reis',
			'Bulgur',
			'Mandeln',
			'Gnocchi',
			'Mandeln, gemahlen',
			'Vollkornwraps',
		],
	},
	DRYSHELF: {
		name: 'Trockenregal',
		items: [
			'Agavendicksaft',
			'Ahornsirup',
			'Apfelessig',
			'Essig',
			'Ei',
			'Eier',
			'Salsa-Sauce',
			'Kokosöl',
			'Kokosmilch, Konserve',
			'Parmesan, gerieben',
			'Kidneybohnen, Konserve',
			'Fettarme Kokosmilch, Konserve',
			'Gemüsebrühe',
			'Limettensaft',
			'Rapsöl',
			'Weißweinessig',
			'Zitronensaft',
			'Pesto Verde',
			'Chilipulver',
			'Currypaste',
			'Currypulver',
			'Mayonnaise',
			'Senf',
			'Sesamöl',
			'Sojasauce',
			'Tomatenmark',
			'Tomatensauce',
			'Vegane Kochcreme',
			'Ajvar',
			'Garam Masala',
			'Rotweinessig',
			'Olivenöl',
		],
	},
	COOLSHELF: {
		name: 'Kühl- / Frischetheke',
		items: [
			'Bockwurst',
			'Wiener Würstchen',
			'Gouda, gerieben',
			'Hähnchenbrustfilets',
			'Halloumi',
			'Cheddar, gerieben',
			'Saure Sahne',
			'Frischkäse',
			'Schinken',
			'Schlagsahne',
			'Schollenfilet',
			'Sojajoghurt',
			'Hüttenkäse',
			'Joghurt, 1,5% Fett',
			'Crème fraîche',
			'Mozzarella',
			'Streukäse, vegan',
			'Feta',
			'Feta, fettarm',
			'Frischkäse, vegan',
			'Räucherlachs',
			'Rinderhackfleisch',
			'Veganes Hackfleisch',
			'Vegetarischer Parmesan, gerieben',
		],
	},
};
